"""add_workout_planning_tables

Revision ID: bd6717b330b9
Revises: bc7e3f0f3c2c
Create Date: 2025-12-17 09:43:00.427905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6717b330b9'
down_revision: Union[str, None] = 'bc7e3f0f3c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_id'), 'training_plans', ['id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.String(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('estimated_tss', sa.Float(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.create_table('planned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_activity_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['completed_activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plannedworkout_user_date', 'planned_workouts', ['user_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_planned_workouts_id'), 'planned_workouts', ['id'], unique=False)
    op.create_index(op.f('ix_planned_workouts_scheduled_date'), 'planned_workouts', ['scheduled_date'], unique=False)
    op.create_table('workout_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('target_power_low', sa.Float(), nullable=True),
    sa.Column('target_power_high', sa.Float(), nullable=True),
    sa.Column('target_power_type', sa.String(), nullable=True),
    sa.Column('target_hr', sa.Integer(), nullable=True),
    sa.Column('interval_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_intervals_id'), 'workout_intervals', ['id'], unique=False)
    op.create_index(op.f('ix_activities_file_hash'), 'activities', ['file_hash'], unique=False)
    op.create_index(op.f('ix_activities_start_time'), 'activities', ['start_time'], unique=False)
    op.create_index(op.f('ix_training_load_date'), 'training_load', ['date'], unique=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_training_load_date'), table_name='training_load')
    op.drop_index(op.f('ix_activities_start_time'), table_name='activities')
    op.drop_index(op.f('ix_activities_file_hash'), table_name='activities')
    op.drop_index(op.f('ix_workout_intervals_id'), table_name='workout_intervals')
    op.drop_table('workout_intervals')
    op.drop_index(op.f('ix_planned_workouts_scheduled_date'), table_name='planned_workouts')
    op.drop_index(op.f('ix_planned_workouts_id'), table_name='planned_workouts')
    op.drop_index('idx_plannedworkout_user_date', table_name='planned_workouts')
    op.drop_table('planned_workouts')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_training_plans_id'), table_name='training_plans')
    op.drop_table('training_plans')
    # ### end Alembic commands ###
