"""Add composite indexes for performance optimization

Revision ID: ea1f410664d0
Revises: a377d02d7377
Create Date: 2025-11-02 18:38:01.259009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1f410664d0'
down_revision: Union[str, None] = 'a377d02d7377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_activity_user_time', 'activities', ['user_id', 'start_time'], unique=False)
    op.create_index('idx_hrzone_activity_label', 'hr_zones', ['activity_id', 'zone_label'], unique=False)
    op.create_index('idx_powerzone_activity_label', 'power_zones', ['activity_id', 'zone_label'], unique=False)
    op.create_index('idx_trainingload_user_date', 'training_load', ['user_id', 'date'], unique=False)
    # Note: Removed alter_column for 'name' - not needed and causes SQLite compatibility issues
    # The 'name' field already exists and works correctly
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trainingload_user_date', table_name='training_load')
    op.drop_index('idx_powerzone_activity_label', table_name='power_zones')
    op.drop_index('idx_hrzone_activity_label', table_name='hr_zones')
    op.drop_index('idx_activity_user_time', table_name='activities')
    # ### end Alembic commands ###
